package com.doak.springbootdemo.entity;

import lombok.ToString;

@ToString
public class Resource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_resource.id
	 * @mbg.generated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_resource.fun_urls
	 * @mbg.generated
	 */
	private String funUrls;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_resource.menu_url
	 * @mbg.generated
	 */
	private String menuUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_resource.res_key
	 * @mbg.generated
	 */
	private String resKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_resource.res_name
	 * @mbg.generated
	 */
	private String resName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_resource.res_type
	 * @mbg.generated
	 */
	private String resType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_resource.status
	 * @mbg.generated
	 */
	private Boolean status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_resource.parent_id
	 * @mbg.generated
	 */
	private Long parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column crm_resource.weight
	 * @mbg.generated
	 */
	private Integer weight;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_resource.id
	 * @return  the value of crm_resource.id
	 * @mbg.generated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_resource.id
	 * @param id  the value for crm_resource.id
	 * @mbg.generated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_resource.fun_urls
	 * @return  the value of crm_resource.fun_urls
	 * @mbg.generated
	 */
	public String getFunUrls() {
		return funUrls;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_resource.fun_urls
	 * @param funUrls  the value for crm_resource.fun_urls
	 * @mbg.generated
	 */
	public void setFunUrls(String funUrls) {
		this.funUrls = funUrls == null ? null : funUrls.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_resource.menu_url
	 * @return  the value of crm_resource.menu_url
	 * @mbg.generated
	 */
	public String getMenuUrl() {
		return menuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_resource.menu_url
	 * @param menuUrl  the value for crm_resource.menu_url
	 * @mbg.generated
	 */
	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl == null ? null : menuUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_resource.res_key
	 * @return  the value of crm_resource.res_key
	 * @mbg.generated
	 */
	public String getResKey() {
		return resKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_resource.res_key
	 * @param resKey  the value for crm_resource.res_key
	 * @mbg.generated
	 */
	public void setResKey(String resKey) {
		this.resKey = resKey == null ? null : resKey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_resource.res_name
	 * @return  the value of crm_resource.res_name
	 * @mbg.generated
	 */
	public String getResName() {
		return resName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_resource.res_name
	 * @param resName  the value for crm_resource.res_name
	 * @mbg.generated
	 */
	public void setResName(String resName) {
		this.resName = resName == null ? null : resName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_resource.res_type
	 * @return  the value of crm_resource.res_type
	 * @mbg.generated
	 */
	public String getResType() {
		return resType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_resource.res_type
	 * @param resType  the value for crm_resource.res_type
	 * @mbg.generated
	 */
	public void setResType(String resType) {
		this.resType = resType == null ? null : resType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_resource.status
	 * @return  the value of crm_resource.status
	 * @mbg.generated
	 */
	public Boolean getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_resource.status
	 * @param status  the value for crm_resource.status
	 * @mbg.generated
	 */
	public void setStatus(Boolean status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_resource.parent_id
	 * @return  the value of crm_resource.parent_id
	 * @mbg.generated
	 */
	public Long getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_resource.parent_id
	 * @param parentId  the value for crm_resource.parent_id
	 * @mbg.generated
	 */
	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column crm_resource.weight
	 * @return  the value of crm_resource.weight
	 * @mbg.generated
	 */
	public Integer getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column crm_resource.weight
	 * @param weight  the value for crm_resource.weight
	 * @mbg.generated
	 */
	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	

	
	
	
}